### ISSUE TITLE
Unexpected error `database or disk is full`

### ISSUE THREAD

**Issue by psychelzh** [PennLINC/xcp_d#1001]
Originally posted on Neurostars as [this](https://neurostars.org/t/unexpected-error-of-database-or-disk-is-full-using-xcp-d/27382).

## Summary

A simple use case of `xcp_d` reported `database or disk is full error` about 3 minutes after it started.

## Additional details

- xcp_d version: `v0.5.2`
- Singularity version: `3.7.0+98-g3a4ca27de`

### What were you trying to do?

Test an example run of my dataset after fmriprep. Here are screenshots of the pre-processed data (each subject has two sessions, and each session contains 6-7 runs of 7-min bold data):

![image](https://github.com/PennLINC/xcp_d/assets/13306020/ba17580e-d839-46e2-b666-4e6fb5990783)

![image](https://github.com/PennLINC/xcp_d/assets/13306020/a22d0a40-1d05-4131-8168-15322ceee8d8)

![image](https://github.com/PennLINC/xcp_d/assets/13306020/10e18c1d-697f-4e7c-88e2-40bed080eb40)

Here is my code:

```bash
singularity run -c -e -B /seastor,/home/zhangliang /opt/fmritools/containers/xcp_d-0.5.2.sif \
  /seastor/CAMP/derivatives/fmriprep /seastor/CAMP/derivatives/example \
  `# filtering bids queries` \
  --participant_label SICNU001 \
  --cifti \
  `# performance options` \
  --nthreads 8 \
  --omp-nthreads 8 \
  --mem_gb 12 \
  `# other options` \
  --work-dir /seastor/CAMP/tmp \
  --notrack \
  `# freesurfere options` \
  --fs-license-file /seastor/zhangliang/license.txt
```

### What actually happened?

It reports an error of `database or disk is full`, and here is the relevant log:

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database or disk is full

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 901, in build_workflow
    layout = BIDSLayout(str(opts.fmri_dir), validate=False, derivatives=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 152, in __init__
    indexer(self)
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/index.py", line 153, in __call__
    self._index_metadata()
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/index.py", line 285, in _index_metadata
    all_files = self._layout.get(absolute_paths=True, **filters)
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 653, in get
    results.extend(query.all())
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full
[SQL: SELECT files.path AS files_path, files.filename AS files_filename, files.dirname AS files_dirname, files.is_dir AS files_is_dir, files.class_ AS files_class_ 
FROM files 
WHERE files.is_dir = 0 GROUP BY files.path]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by psychelzh** [comment]
Given that I have plenty of disk quota, and the `/tmp` directory also has enough quota, I am wondering if it is a bug of `xcp_d`.

**Comment by psychelzh** [comment]
Based on https://github.com/nipreps/fmriprep/issues/2525, it is best to pre-compute BIDS database. Hopefully, this might be solved after #954.

**Comment by psychelzh** [comment]
Interestingly, the following command succeeded:

```bash
singularity exec -C -e -B /seastor,/home/zhangliang /opt/fmritools/containers/xcp_d-0.5.2.sif pybids layout /seastor/CAMP/derivatives/fmriprep /seastor/CAMP/test --no-validate
# Successfully generated database index at /seastor/CAMP/test
```

So I am wondering why workflow will fail.

**Comment by tsalo** [comment]
Thanks for following up with your solution. @mattcieslak do you have any idea why `-C`/`-c` would be a problem for XCP-D?
