### ISSUE TITLE
`No anat_to_native_xfm`

### ISSUE THREAD

**Issue by smeisler** [PennLINC/xcp_d#1002]
## Summary

XCP_D fails to find anatomical transforms. Tree of fMRIPrep outputs below:

```
.
├── dataset_description.json
├── desc-aparcaseg_dseg.tsv
├── desc-aseg_dseg.tsv
├── logs
│   ├── CITATION.bib
│   ├── CITATION.html
│   ├── CITATION.md
│   └── CITATION.tex
├── sub-00582981
│   ├── figures
│   │   ├── sub-00582981_ses-00_acq-gre_run-1_fmapid-auto00000_desc-phasediff_fieldmap.svg
│   │   ├── sub-00582981_ses-00_acq-mpr_run-1_desc-conform_T1w.html
│   │   ├── sub-00582981_ses-00_acq-mpr_run-1_desc-reconall_T1w.svg
│   │   ├── sub-00582981_ses-00_acq-mpr_run-1_dseg.svg
│   │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_T1w.svg
│   │   ├── sub-00582981_ses-00_desc-about_T1w.html
│   │   ├── sub-00582981_ses-00_desc-summary_T1w.html
│   │   ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-carpetplot_bold.svg
│   │   ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-compcorvar_bold.svg
│   │   ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-confoundcorr_bold.svg
│   │   ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-coreg_bold.svg
│   │   ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-fmapCoreg_bold.svg
│   │   ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-rois_bold.svg
│   │   ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-sdc_bold.svg
│   │   ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-summary_bold.html
│   │   └── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-validation_bold.html
│   ├── log
│   │   └── 20231204-210201_8db5dd19-b896-4fcd-b942-d0660220b05c
│   │       └── fmriprep.toml
│   └── ses-00
│       ├── anat
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_desc-brain_mask.json
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_desc-brain_mask.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_desc-preproc_T1w.json
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_desc-preproc_T1w.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_desc-ribbon_mask.json
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_desc-ribbon_mask.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_dseg.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_from-fsnative_to-T1w_mode-image_xfm.txt
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_from-T1w_to-fsnative_mode-image_xfm.txt
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_desc-reg_sphere.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_midthickness.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_pial.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_space-fsLR_desc-msmsulc_sphere.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_space-fsLR_desc-reg_sphere.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_sphere.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_sulc.shape.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_thickness.shape.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-L_white.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_desc-reg_sphere.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_midthickness.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_pial.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_space-fsLR_desc-msmsulc_sphere.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_space-fsLR_desc-reg_sphere.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_sphere.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_sulc.shape.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_thickness.shape.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_hemi-R_white.surf.gii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_label-CSF_probseg.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_label-GM_probseg.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_label-WM_probseg.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_curv.dscalar.nii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_curv.json
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_sulc.dscalar.nii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_sulc.json
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_thickness.dscalar.nii
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_thickness.json
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.json
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_desc-preproc_T1w.json
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_dseg.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
│       │   ├── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
│       │   └── sub-00582981_ses-00_acq-mpr_run-1_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
│       ├── fmap
│       │   ├── sub-00582981_ses-00_acq-gre_run-1_fmapid-auto00000_desc-coeff0_fieldmap.nii.gz
│       │   ├── sub-00582981_ses-00_acq-gre_run-1_fmapid-auto00000_desc-coeff1_fieldmap.nii.gz
│       │   ├── sub-00582981_ses-00_acq-gre_run-1_fmapid-auto00000_desc-magnitude_fieldmap.nii.gz
│       │   ├── sub-00582981_ses-00_acq-gre_run-1_fmapid-auto00000_desc-preproc_fieldmap.json
│       │   └── sub-00582981_ses-00_acq-gre_run-1_fmapid-auto00000_desc-preproc_fieldmap.nii.gz
│       └── func
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-brain_mask.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-brain_mask.nii.gz
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-confounds_timeseries.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-confounds_timeseries.tsv
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-coreg_boldref.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-coreg_boldref.nii.gz
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-hmc_boldref.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-hmc_boldref.nii.gz
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-preproc_bold.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-preproc_bold.nii.gz
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_from-boldref_to-auto00000_mode-image_xfm.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_from-boldref_to-auto00000_mode-image_xfm.txt
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_from-orig_to-boldref_mode-image_desc-hmc_xfm.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-fsLR_den-91k_bold.dtseries.nii
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-fsLR_den-91k_bold.json
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_boldref.nii.gz
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
│           ├── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.json
│           └── sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
└── sub-00582981.html
```
## Additional details

- xcp_d version: 0.6.0rc6
- fmriprep version: 23.2.0rc2 (no errors)
- Singularity version: Apptainer 1.1.7
- Additionally, when I try to move the `anat` folder to one level higher (that is, on the same level as the `ses-XX` folder), a copy of `anat` is placed back within the `ses-XX` folder, leading to an error of duplicate files which also causes XCP_D to crash.
### What actually happened?
```
231205-10:29:33,802 nipype.workflow IMPORTANT:
	 Running xcp_d version 0.6.0rc6:
    * fMRI directory path: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep.
    * Participant list: ['00582981'].
    * Run identifier: 20231205-102933_a0abbea1-21f0-4dda-96d5-e9ab377cb164.


231205-10:29:34,212 nipype.utils IMPORTANT:
	 Collected data:
anat_brainmask: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_desc-brain_mask.nii.gz
anat_dseg: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_dseg.nii.gz
anat_to_template_xfm: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
bold:
- /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/func/sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
t1w: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_desc-preproc_T1w.nii.gz
t2w: null
template_to_anat_xfm: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5

231205-10:29:34,383 nipype.utils IMPORTANT:
	 Collected mesh files:
lh_pial_surf: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_hemi-L_pial.surf.gii
lh_wm_surf: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_hemi-L_white.surf.gii
rh_pial_surf: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_hemi-R_pial.surf.gii
rh_wm_surf: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_hemi-R_white.surf.gii

231205-10:29:34,501 nipype.utils IMPORTANT:
	 Collected morphometry files:
cortical_thickness: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_thickness.dscalar.nii
cortical_thickness_corr: null
myelin: null
myelin_smoothed: null
sulcal_curv: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_curv.dscalar.nii
sulcal_depth: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/anat/sub-00582981_ses-00_acq-mpr_run-1_space-fsLR_den-91k_sulc.dscalar.nii

231205-10:29:34,925 nipype.utils IMPORTANT:
	 Collected run data for sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz:
anat_to_native_xfm: null
boldmask: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/func/sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
boldref: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/func/sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_boldref.nii.gz
confounds: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/func/sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-confounds_timeseries.tsv
confounds_json: /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/func/sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_desc-confounds_timeseries.json

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 977, in build_workflow
    retval["workflow"] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/base.py", line 199, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/base.py", line 671, in init_subject_wf
    run_data = collect_run_data(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/bids.py", line 654, in collect_run_data
    raise FileNotFoundError(f"No {k} file found for {bids_file.path}")
FileNotFoundError: No anat_to_native_xfm file found for /om2/scratch/tmp/smeisler/mri_proc/sub-00582981/data/derivatives/fmriprep/sub-00582981/ses-00/func/sub-00582981_ses-00_task-rest_acq-ep2d_dir-AP_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz

```
## Reproducing the bug
1. Run fMRIPrep 23.2.0rc2
```
singularity run -e --containall -B ${scratch},${templateflow_dir},${cache_dir} \
 $fmriprep_IMG --participant_label ${subject:4} -w $scratch \
 --fs-license-file ${scratch}/license.txt --fs-subjects-dir ${scratch}/data/derivatives/freesurfer/ \
--project-goodvoxels --notrack --cifti-output 91k --slice-time-ref 0 \
--use-syn-sdc --mem_mb ${mem_mb} --nprocs ${nprocs} --omp-nthreads ${omp_nprocs} \
$scratch/data $scratch/data/derivatives/fmriprep participant
```
2. Run XCP_D 0.6.0rc6 
```
singularity run -e --containall -B ${scratch},${templateflow_dir},${cache_dir} \
$xcp_IMG --nthreads ${nprocs} --omp-nthreads ${omp_nprocs} --despike \
-w $scratch --fs-license-file ${scratch}/license.txt --notrack \
${scratch}/data/derivatives/fmriprep ${scratch}/data/derivatives/ participant 
```

**Comment by tsalo** [comment]
Oh, I guess it'll take a bit more effort than I thought. fMRIPrep now only writes out the boldref-to-anat transform (i.e., no anat-to-boldref transform), although it can be inverted easily enough.

**Comment by tsalo** [comment]
It looks like the anat-to-native transform was only retained as an artifact of back when XCP-D ostensibly supported native-space preprocessed BOLD data. Since we don't support that anymore (and maybe never successfully did), I'm just going to cut out everything related to native-space data.
