### ISSUE TITLE
Help w/ bold registration import for Nibabies inputs

### ISSUE THREAD

**Issue by ajdneuro** [PennLINC/xcp_d#1059]
## Summary
I am getting the following error when importing Nibabies outputs, I was wondering if someone could help me decipher what was going on.

I ran a participant with nibabies: 
```
nibabies-wrapper singularity /home/exacloud/gscratch/IGNLab/MHM_data/bids_dir /home/exacloud/gscratch/IGNLab/MHM_data/out_dir participant -i /home/exacloud/gscratch/IGNLab/singularity_scripts/nibabies_latest.sif -w /home/exacloud/gscratch/IGNLab/MHM_data/work_dir --fs-license-file /home/exacloud/gscratch/IGNLab/freesurfer/license.txt --skip_bids_validation --age-months 1 --cifti-output --output-spaces MNI152NLin2009cAsym 
```

Then w/ XCP-D: 

## Additional details

- xcp_d version: 0.5.0
- Docker version:
- Singularity version: 3.8.0

### What did you expect to happen?
```
singularity run -B $HOME:/home/xcp --home /home/xcp -B /home/exacloud/gscratch/IGNLab/MHM_data/out_dir:/fmri_dir -B /home/exacloud/gscratch/IGNLab/MHM_data/xcpd_workdir:/workdir -B /home/exacloud/gscratch/IGNLab/MHM_data/xcpd_outdir:/outdir /home/exacloud/gscratch/IGNLab/singularity_scripts/xcp_d-0.5.0.sif /fmri_dir /outdir participant --participant_label sub-M80302901 --input-type nibabies -p 36P -w /workdir --despike --combineruns --smoothing 6 --dummy_scans auto --head_radius auto
```

### What actually happened?
Error message:
```
1w_to-scanner_mode-image_xfm.txt
boldmask: /fmri_dir/sub-M80302901/func/sub-M80302901_task-riserestap32chmb82mmLrgFOVv01r01_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
boldref: /fmri_dir/sub-M80302901/func/sub-M80302901_task-riserestap32chmb82mmLrgFOVv01r01_run-1_space-MNI152NLin2009cAsym_boldref.nii.gz
confounds: /fmri_dir/sub-M80302901/func/sub-M80302901_task-riserestap32chmb82mmLrgFOVv01r01_run-1_desc-confounds_timeseries.tsv
confounds_json: /fmri_dir/sub-M80302901/func/sub-M80302901_task-riserestap32chmb82mmLrgFOVv01r01_run-1_desc-confounds_timeseries.json

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 990, in build_workflow
    retval["workflow"] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/base.py", line 199, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/base.py", line 716, in init_subject_wf
    postprocess_bold_wf = init_postprocess_bold_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/bold.py", line 573, in init_postprocess_nifti_wf
    execsummary_functional_plots_wf = init_execsummary_functional_plots_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/execsummary.py", line 384, in init_execsummary_functional_plots_wf
    bold_t1w_registration_file = fnmatch.filter(
IndexError: list index out of range
```

Thank you for your help!!

Best,
Alex

**Comment by ajdneuro** [comment]
That worked! Many thanks!

**Comment by tsalo** [comment]
:+1:
