### ISSUE TITLE
ConnectPlot TypeError: 'Axes' object is not subscriptable

### ISSUE THREAD

**Issue by baxpr** [PennLINC/xcp_d#1187]
@tsalo 

Hi Taylor. I'm running into an error in new code in 0.7.4 in connectivity.py ConnectPlot:

https://github.com/PennLINC/xcp_d/blame/bb0271841cd3c5400c2e9b7675a7e1784060cdee/xcp_d/interfaces/connectivity.py#L849

```
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node connectivity_plot.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/interfaces/connectivity.py", line 849, in _run_interface
	    ax = axes[sel_ax_idx]
	TypeError: 'Axes' object is not subscriptable
```

Command line options were

```
--skip-dcan-qc 
--smoothing 0 
--atlases Glasser 
--nuisance-regressors acompcor 
--fd-thresh 0.3 
--min-time 300 
--exact-time 300 
--lower-bpf 0.01 
--upper-bpf 0.10 
--min-coverage 0.5
```

**Comment by baxpr** [comment]
This is using the 0.7.4 docker container by the way, pennlinc/xcp_d:0.7.4

**Comment by tsalo** [comment]
Thanks for reporting this @baxpr. I think #1188 should fix it, so I'll merge that once CI passes and make a patch release.
