### ISSUE TITLE
Using an external atlas creates an error when loading built-in xcp_d atlases.

### ISSUE THREAD

**Issue by gagnonanthony** [PennLINC/xcp_d#1303]
## Summary

Hi all, 

I am running `xcp_d` following `fmriprep` using a custom atlas (Brainnetome Child, fsLR-32k). Here is the structure of my external atlas folder:
```bash
atlases
└── brainnetome
    ├── atlas-BrainnetomeChild
    │   ├── atlas-BrainnetomeChild_dseg.tsv
    │   ├── atlas-BrainnetomeChild_space-fsLR_den-32k_dseg.dlabel.nii
    │   └── atlas-BrainnetomeChild_space-fsLR_den-32k_dseg.json
    └── dataset_description.json
```

`xcp_d` does seem to be able to read, collect, and load the external atlas (BrainnetomeChild). However, it prompts an error when loading a built-in `xcp_d` atlas (it also prompts this error when only selecting my external atlas). See the log file:
```bash
2024-10-24 14:39:35,414 [    INFO] Loading atlas: BrainnetomeChild
2024-10-24 14:39:35,414 [    INFO] Loading atlas: Glasser
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/cli/workflow.py", line 100, in build_workflow
    retval["workflow"] = init_xcpd_wf()
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/workflows/base.py", line 81, in init_xcpd_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/workflows/base.py", line 353, in init_single_subject_wf
    parcellate_surfaces_wf = init_parcellate_surfaces_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/workflows/anatomical/parcellation.py", line 86, in init_parcellate_surfaces_wf
    builtin_atlases = select_atlases(atlases=config.execution.atlases, subset="all")
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/utils/atlas.py", line 53, in select_atlases
    assert all([atlas in BUILTIN_ATLASES["all"] for atlas in atlases])
AssertionError
```

When I remove my external atlas in my command, `xcp_d` runs fine without errors. I suspect this assertion in `utils/atlas.py` might be the root cause of this error (I might be wrong) as it tries to assert the supplied atlas is found within the built-in atlases:
```python
assert all([atlas in BUILTIN_ATLASES["all"] for atlas in atlases])
```

## Additional details

- xcp_d version: latest (I believe it is 0.10.0-rc1)
- Apptainer version: 1.2.4

### What were you trying to do?

Compute functional connectivity using a custom atlas.

### What did you expect to happen?

Compute functional connectivity using both my custom atlas and Glasser atlas. 

### What actually happened?

Crash when loading the built-in `xcp_d` atlas.

## Reproducing the bug

Here is the command I use:
```bash
#!/bin/bash
#
#SBATCH -J xcpd
#SBATCH --time=24:00:00
#SBATCH -n 1
#SBATCH --cpus-per-task=16
#SBATCH --mem=31G
# Outputs ----------------------------------
#SBATCH -o log/%x-%A-%a.out
#SBATCH -e log/%x-%A-%a.err
#SBATCH --mail-user=Anthony.Gagnon7@usherbrooke.ca
#SBATCH --mail-type=ALL
# ------------------------------------------

BIDS_DIR="$STUDY/fMRI_data"
FMRIPREP_DIR="$BIDS_DIR/derivatives/fmriprep-24.1.1"
DERIVS_DIR="$BIDS_DIR/derivatives/xcpd-0.10.0"
SCRATCH="$STUDY/temp/"

# Prepare some writeable bind-mount points.
TEMPLATEFLOW_HOST_HOME=$HOME/templateflow
mkdir -p ${TEMPLATEFLOW_HOST_HOME}

# Prepare derivatives folder
mkdir -p ${DERIVS_DIR}

# Make sure FS_LICENSE is defined in the container.
export APPTAINERENV_FS_LICENSE=$STUDY/license.txt

# Designate a templateflow bind-mount point
export APPTAINERENV_TEMPLATEFLOW_HOME="/templateflow"
APPTAINER_CMD="apptainer run --cleanenv -B ${FMRIPREP_DIR}:/fmriprep -B ${TEMPLATEFLOW_HOST_HOME}:${APPTAINERENV_TEMPLATEFLOW_HOME} -B ${SCRATCH}:/work -B ${DERIVS_DIR}:/out -B ${STUDY}/atlases/brainnetome:/brainnetome ${STUDY}/xcp-d_0.10.0-mp2.sif"

# Parse the participants.tsv file and extract one subject ID from the line corresponding to this SLURM task.
subject=$( sed -n -E "$((${SLURM_ARRAY_TASK_ID} + 1))s/sub-(\S*)\>.*/\1/gp" ${BIDS_DIR}/participants.tsv )

# Compose the command line
cmd="${APPTAINER_CMD} /fmriprep /out participant --participant-label $subject -w /work -v -t rest --datasets brainnetome=/brainnetome --atlases BrainnetomeChild Glasser --omp-nthreads 8 --nthreads 16 --mem_gb 30 --mode abcd --motion-filter-type notch --band-stop-min 15 --band-stop-max 25 --create-matrices all"

# Setup done, run the command
echo Running task ${SLURM_ARRAY_TASK_ID}
echo Commandline: $cmd
eval $cmd
exitcode=$?

# Output results to a table
echo "sub-$subject   ${SLURM_ARRAY_TASK_ID}    $exitcode" \
      >> ${SLURM_JOB_NAME}.${SLURM_ARRAY_JOB_ID}.tsv
echo Finished tasks ${SLURM_ARRAY_TASK_ID} with exit code $exitcode
exit $exitcode
```
Cheers!

**Comment by tsalo** [comment]
Wow, that's a very silly mistake. Thanks for reporting @gagnonanthony! I'll push a fix ASAP.

**Comment by gagnonanthony** [comment]
Amazing, thank you @tsalo!
