### ISSUE TITLE
-m / --combineruns argument not recognized

### ISSUE THREAD

**Issue by smeisler** [PennLINC/xcp_d#266]
This is using the latest stable release (0.8.0) on Singularity; code runs fine without it.

**Comment by a3sha2** [comment]
can you try `xcp_abcd:unstable`? it was not implemented in 0.0.8

**Comment by smeisler** [comment]
The argument was recognized. I will update further when I have a complete run, but am currently stuck on another issue (#267)

**Comment by smeisler** [comment]
XCP will run with the `-m` argument, but the outputs are still kept separate.

**Comment by smeisler** [comment]
I see this error at the very end (when including the `-m` flag):
```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_abcd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/cli/run.py", line 297, in main
    failed_reports = generate_reports(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/interfaces/report_core.py", line 95, in generate_reports
    concatenatebold(subjlist=subject_list,fmridir=str(fmri_dir),outputdir=Path(str(output_dir))/'xcp_abcd/',cifti=cifti)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/utils/concantenation.py", line 27, in concatenatebold
    listout = concatenate_nifti(subid=_prefix(s),fmridir=fmridir,outputdir=outputdir)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/utils/concantenation.py", line 120, in concatenate_nifti
    return [precarpet,postcarpet,gboldbbreg,bboldref]
UnboundLocalError: local variable 'precarpet' referenced before assignment
```

**Comment by a3sha2** [comment]
@smeisler  thanks , working on this error

**Comment by a3sha2** [comment]
pls try the latest unstable one

**Comment by smeisler** [comment]
Hi, I am getting the following error when reaching the final concatenation stage (subject HTML report says "no errors to report" but the crash happens before executive summary HTMLs are made).

```
Concatenating bold files ...
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_abcd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/cli/run.py", line 295, in main
    failed_reports = generate_reports(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/interfaces/report_core.py", line 100, in generate_reports
    concatenatebold(subjlist=subject_list,fmridir=str(fmri_dir),outputdir=Path(str(output_dir))/'xcp_abcd/')
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/utils/concantenation.py", line 16, in concatenatebold
    fmr = glob.glob(str(outdir) + '/' + _prefix(subjlist[0])+'/*/func/*_desc-residual_bold*nii*')[0]
IndexError: list index out of range
``` 

This happens because I have a resolution specifier (`res-2`) on my bold files, so the XCP output looks like this:
![image](https://user-images.githubusercontent.com/27028726/147977945-db4aec64-eaa6-4194-9974-cb4f56508fe1.png)
Note how `res-2` comes between `residual` and `bold`, making `fmr` empty.

**Comment by a3sha2** [comment]
thank you, I understand what went wrong now
