### ISSUE TITLE
-p Argument not loaded correctly

### ISSUE THREAD

**Issue by smeisler** [PennLINC/xcp_d#267]
Using latest stable release (0.0.8) on singularity
**Command**:
`singularity run -B ${scratch},${bids_dir} $IMG ${output_dir}/fmriprep ${output_dir} participant --participant_label ${subject:4} -w $scratch -p acompcor -f 1 --smoothing 0`

**Error:**
  ```
  Running xcp_abcd version 0.0.8+0.g88e3ec9.dirty:
      * fMRIPrep directory path: /om4/group/gablab/data/ds003126/derivatives/fmriprep.
      * Participant list: ['047EPKL011012'].
      * Run identifier: 20211211-114648_a665f222-9149-4b16-8fe3-32e5863f62a3.

    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/cli/run.py", line 485, in build_workflow
    retval['workflow'] = init_xcpabcd_wf (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/base.py", line 147, in init_xcpabcd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/base.py", line 403, in init_subject_wf
    bold_postproc_wf = init_boldpostprocess_wf(bold_file=bold_file,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/bold.py", line 219, in init_boldpostprocess_wf
    """.format(regressors=stringforparams(params=params),sclver=sklearn.__version__,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/utils/utils.py", line 197, in stringforparams
    return bsignal
UnboundLocalError: local variable 'bsignal' referenced before assignment
```

Based on looking at the utils.py script, it looks like the -p argument isn't properly loaded as the `params` variable. Code runs fine when leaving this option blank and using the 27P default parameter set, but I'd like to use acompcor.

Thanks,
Steven

**Comment by a3sha2** [comment]
can you try `xcp_abcd:unstable`?

**Comment by smeisler** [comment]
It looks like it is running and using acompcor, however, the way it looks for components might be outdated with fMRIPrep's new release. Compartment specific components are now coded as "`c_comp_corXX`" for CSF and "`w_comp_corXX`" for WM. I get the following error when running on a fMRIPrep 21.0.0rc2-processed dataset:

```
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ConfoundMatrix_wf.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/interfaces/confound.py", line 83, in _run_interface
    data_matrix = load_confound_matrix(datafile=self.inputs.in_file,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/utils/confounds.py", line 140, in load_confound_matrix
    acompc = load_acompcor(confoundspd=confoundtsv, confoundjs=confoundjson)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/utils/confounds.py", line 75, in load_acompcor
    csflist.append(CSF[i][0])
IndexError: list index out of range

```

I have checked that the runs do have at least 5 compartment specific components so it is not that is indexing too high of a component, it is just using an old name convention.

Also, the boilerplate and documentation seem to offer different strategies: The boiler plate says  

> All the components of the aCompCor algorithm were selected as  nuisance regressor

While the documentation suggests 5 of each compartment are selected. The boilerplate suggests all components that explain 50% variance are selected.
