### ISSUE TITLE
Nibabies error bold t1w reg

### ISSUE THREAD

**Issue by ajdneuro12** [PennLINC/xcp_d#300]
Hi, thanks for this exciting tool! 

I am trying to run a participant that I ran throught Nibabies and getting this error, any ideas would be great!:

My command was:  singularity run --cleanenv ../singularity_images/xcp_d-0.0.9.simg nibabies_output/ xcpd_output/

   Running xcp_abcd version 0.0.9+0.g067fabf.dirty:
      * fMRI directory path: /gpfs/ysm/project/scheinost/ajd224/bcpraw/nibabies_output.
      * Participant list: ['NDARAA604ZHR'].
      * Run identifier: 20220402-183939_50d0f120-7b08-4880-99dd-17dd51f98532.

    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 486, in build_workflow
    retval['workflow'] = init_xcpd_wf (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 145, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 396, in init_subject_wf
    bold_postproc_wf = init_boldpostprocess_wf(bold_file=bold_file,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/bold.py", line 290, in init_boldpostprocess_wf
    executivesummary_wf =init_execsummary_wf(tr=TR,bold_file=bold_file,layout=layout,mem_gb=mem_gbx['timeseries'],
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/execsummary.py", line 44, in init_execsummary_wf
    bold_t1w_reg = fnmatch.filter(all_files, '*' + prefixbb + coregbbregfile[0])[0]
IndexError: list index out of range

**Comment by kahinimehta** [comment]
Hello! Sorry for the late response. This error can happen if XCP can't find the  bbregister/coregister file in the outputs - my first idea would be to see if you could locate this file and confirm it's accessible in the directory fed to XCP/ in standard BIDS format?
