### ISSUE TITLE
UnboundLocalError: local variable ‘confound’ referenced before assignment

### ISSUE THREAD

**Issue by eburkevt** [PennLINC/xcp_d#326]
I downloaded the latest singularity version of xcp_d, but I am still getting the following error  ...

_UnboundLocalError: local variable ‘confound’ referenced before assignment_

... it appears to be the same error as described in #319, but updating to the latest singularity version of xcp_d did not appear to solve the issue. 

I updated using 

_singularity build xcp_d-latest.simg docker://pennlinc/xcp_d:latest_

Which version of the docker/singularity image should we download?

**Comment by eburkevt** [comment]
Update on xcp_d:lastest version, still getting errors on multiple subjects even after clearing work directory. The latest version is 

    Running xcp_abcd version 0.0.9+0.g067fabf.dirty:

This is the current error I'm getting

220527-14:13:36,780 nipype.workflow INFO:
	 [Node] Finished "ConfoundMatrix_wf", elapsed time 0.2717s.
220527-14:13:36,780 nipype.workflow WARNING:
	 Storing result file without outputs
220527-14:13:36,828 nipype.workflow WARNING:
	 [Node] Error on "xcpabcd_wf.single_subject_hcS1252HGX_wf.bold_postprocess_1_wf.ConfoundMatrix_wf" (/onrc/home/pipeline/data/pipelineb/home/Chyatt/onrc/data/fmriprep/work_xcp-d/xcpabcd_wf/single_subject_hcS1252HGX_wf/bold_postprocess_1_wf/ConfoundMatrix_wf)
220527-14:13:38,216 nipype.workflow ERROR:
	 Node ConfoundMatrix_wf failed to run on host mica.
220527-14:13:38,229 nipype.workflow ERROR:
	 Saving crash info to /onrc/home/pipeline/data/pipelineb/home/Chyatt/onrc/data/fmriprep/rest900yale/derivatives/fmriprep/sub-hcS1252HGX/xcp_d/sub-hcS1252HGX/log/crash-20220527-141338-Chyatt-ConfoundMatrix_wf-5e07a895-e28f-49c1-b711-0ba79ca6ffc9.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ConfoundMatrix_wf.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/confound.py", line 83, in _run_interface
    data_matrix = load_confound_matrix(datafile=self.inputs.in_file,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/confounds.py", line 168, in load_confound_matrix
    return confound
UnboundLocalError: local variable 'confound' referenced before assignment

I'm going to try the unstable version.

**Comment by eburkevt** [comment]
I tried 'unstable.' It got much further in the processing, but a new error appears ...

Node: xcpabcd_wf.single_subject_hcS1252HGX_wf.anatomical_wf.left_pial_surf
Working directory: /onrc/home/pipeline/data/pipelineb/home/Chyatt/onrc/data/fmriprep/work_xcp-d/xcpabcd_wf/single_subject_hcS1252HGX_wf/anatomical_wf/left_pial_surf

Node inputs:

args = <undefined>
current_sphere = <undefined>
environ = {}
in_file = /onrc/home/pipeline/data/pipelineb/home/Chyatt/onrc/data/fmriprep/rest900yale/derivatives/fmriprep/sub-hcS1252HGX/xcp_d/sub-hcS1252HGX/anat/sub-hcS1252HGX_space-fsLR_den-32k_hemi-L_pial.surf.gii
metric =  BARYCENTRIC 
new_sphere = /home/Chyatt/.cache/templateflow/tpl-fsLR/tpl-fsLR_hemi-L_den-32k_sphere.surf.gii
out_file = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node left_pial_surf.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_file' trait of a CiftiSurfaceResampleOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/onrc/home/pipeline/data/pipelineb/home/Chyatt/onrc/data/fmriprep/work_xcp-d/xcpabcd_wf/single_subject_hcS1252HGX_wf/anatomical_wf/left_pial_surf/resampled_sub-hcS1252HGX_space-fsLR_den-32k_hemi-L_pial.surf-MNIaffine-MNIwarped.surf.gii' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/onrc/home/pipeline/data/pipelineb/home/Chyatt/onrc/data/fmriprep/work_xcp-d/xcpabcd_wf/single_subject_hcS1252HGX_wf/anatomical_wf/left_pial_surf/resampled_sub-hcS1252HGX_space-fsLR_den-32k_hemi-L_pial.surf-MNIaffine-MNIwarped.surf.gii' for output 'out_file' of a CiftiSurfaceResample interface

**Comment by eburkevt** [comment]
> Do you have the freesurfer directory available?
> 
> yes, sorry, for quick bug fixes it will always be the unstable.

Yes, this subject had the freesurfer folder/data.

**Comment by kahinimehta** [comment]
Hello @eburkevt, I just wanted to confirm that this issue was resolved for you with version 0.1.2?

**Comment by eburkevt** [comment]
> Hello @eburkevt, I just wanted to confirm that this issue was resolved for you with version 0.1.2?

Thanks for your reply.  I haven't followed up on this issue since May and decided to use a different set of packages for fMRI noise reduction.

**Comment by kahinimehta** [comment]
Thanks for letting me know!
