### ISSUE TITLE
traits.trait_errors.TraitError: Each element of the 'transforms' trait of a _FixTraitApplyTransformsInputSpec instance 

### ISSUE THREAD

**Issue by cfilippi4** [PennLINC/xcp_d#364]
When I run xcp_d I'm getting an error and I can't tell what the error is. Can you assist? 

Some details...
I'm running xcp-d on a dataset preprocessed with nibabies.
Our HPC has installed via singularity. 

The error log file reads....
$ cat swarm_42727342_1.e[+] Loading xcp_d  0.0.9  on cn0862 
[-] Unloading singularity  3.8.5-1  on cn0862 
[+] Loading singularity  3.8.5-1  on cn0862 
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_desc-brain_T1w.nii.gz
419B [00:00, 50.2kB/s]                   
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_desc-LR_T1w.nii.gz
692B [00:00, 29.0kB/s]                   
Downloading https://templateflow.s3.amazonaws.com/tpl-fsLR/tpl-fsLR_hemi-L_den-32k_sphere.surf.gii
550B [00:00, 7.81kB/s]                   
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-carpet_dseg.nii.gz
441B [00:00, 34.6kB/s]                   
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 486, in build_workflow
    retval['workflow'] = init_xcpd_wf (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 145, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 396, in init_subject_wf
    bold_postproc_wf = init_boldpostprocess_wf(bold_file=bold_file,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/bold.py", line 320, in init_boldpostprocess_wf
    resample_bold2MNI = pe.Node(ApplyTransforms(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/ants/base.py", line 73, in __init__
    super(ANTSCommand, self).__init__(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 627, in __init__
    super(CommandLine, self).__init__(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/has_traits.py", line 1434, in trait_set
    setattr(self, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 425, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_types.py", line 2515, in validate
    return TraitListObject(self, object, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_list_object.py", line 582, in __init__
    super().__init__(
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_list_object.py", line 213, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_list_object.py", line 213, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_handlers.py", line 873, in validate
    return self.slow_validate(object, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_handlers.py", line 881, in slow_validate
    self.error(object, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'transforms' trait of a _FixTraitApplyTransformsInputSpec instance must be a pathlike object or string representing an existing file or 'identity', but a value of '/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/data/transform/infant_to_2009_Compoiste.h5' <class 'str'> was specified.

cat swarm_42727342_1.o
---- COMMAND EXECUTED: ---------------------------------------------------------
(   let "rnd = 20782 % 10" ; sleep ${rnd} ;             export TMPDIR=/data/NIMH_scratch/filippica/xcp/OIT;             mkdir -p /tmp/sub-OIT179.wrk ;             module load xcp_d ; 	    xcp_d /data/filippica/R21//derivatives/OIT/nibabies_0/sub-OIT179.out /data/filippica/R21//xcpOutput --participant-label sub-OIT179 -t rest --combineruns -v --despike --nuissance-regressors 36P --smoothing 6 --head_radius 35 --fd-thresh .25 -w ${TMPDIR}/sub-OIT179.wrk --notrack --omp-nthreads 1 ;             rm -r ${TMPDIR}/sub-OIT179.wrk )
--------------------------------------------------------------------------------
220628-12:00:21,682 nipype.workflow IMPORTANT:
	 
    Running xcp_abcd version 0.0.9+0.g067fabf.dirty:
      * fMRI directory path: /gpfs/gsfs10/users/filippica/R21/derivatives/OIT/nibabies_0/sub-OIT179.out.
      * Participant list: ['OIT179'].
      * Run identifier: 20220628-120019_60e219bb-8da0-444f-9ea8-06dcc27684d6.

    
220628-12:00:24,168 nipype.utils WARNING:
	 A newer version (1.8.1) of nipy/nipype is available. You are using 1.7.0

Happy to provide any other details that might be useful for identifying the issue.

**Comment by kahinimehta** [comment]
Hi! Could you try using xcp_d with the unstable tag and letting me know if the error persists? Thanks!

**Comment by kahinimehta** [comment]
Hello, sorry for the late response! We believe the error should be fixed in our latest "unstable" tag - let us know if this is not the case and we can have another look!
