### ISSUE TITLE
dummy time could not work

### ISSUE THREAD

**Issue by weiwei-wch** [PennLINC/xcp_d#410]
Hi,
I use xcp_d 0.1.2 to do post-processing of my fmri data pre-processed by fmriprep 22.0.0, while when I set the -d parameter xcp_d could not work properly, my command is:
` docker run --rm -it -u 1001:1001 \
-v fmriprep_result:/data/ \
-v xcp-d_tmp:/wkdir \
-v xcp-d_result:/out \
pennlinc/xcp_d:0.1.2 \
/data /out \
--participant-label 001 \
--despike  --head_radius 50 -w /wkdir -p 36P -d 8`

and the error message is:
` could not run node: xcpd_wf.single_subject_PTSDHQ001_wf.bold_postprocess_1_wf.remove_dummy_time
220811-15:27:20,273 nipype.workflow ERROR:
	 could not run node: xcpd_wf.single_subject_PTSDHQ001_wf.bold_postprocess_2_wf.remove_dummy_time
xcp_d failed: 2 raised. Re-raising first.

 All tasks completed
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node remove_dummy_time.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/prepostcleaning.py", line 122, in _run_interface
    custom_confounds_tsv_undropped = pd.read_table(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 689, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'None'
`

**Comment by kahinimehta** [comment]
Hello! This error message just reflects that no custom confounds .tsv is found, but the workflow should continue to run regularly and the fmriprep confounds .tsv / bold file should still be appropriately censored.

However, we have just pushed an 'unstable' version that causes a more graceful message to appear when no custom confounds are provided, and this should be ready to pull in a few hours.
