### ISSUE TITLE
plot_svgx does not handle censored/shortened data correctly

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#589]
## Summary

When dummytime removal has been performed, `plot_svgx` grabs the _first_ N volumes instead of the last.
When censoring has been performed, it completely ignores the censored volumes and overrides the censored DVARS data with the raw DVARS:

https://github.com/PennLINC/xcp_d/blob/71e8327ebff84e8158e326cfd2f809424b46bf56/xcp_d/utils/plot.py#L513-L517

## Additional details

- xcp_d version: 0.1.3

### What were you trying to do?

Run a test where the FD threshold is strict enough to censor at least some volumes.

### What did you expect to happen?

For the figure to show the censored DVARS.

### What actually happened?

An exception was raised:

```
Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/surfplotting.py", line 202, in _run_interface
	    'after_process'] = plot_svgx(
	  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/plot.py", line 520, in plot_svgx
	    DVARS_timeseries = pd.DataFrame({
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/core/frame.py", line 529, in __init__
	    mgr = init_dict(data, index, columns, dtype=dtype)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 287, in init_dict
	    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 80, in arrays_to_mgr
	    index = extract_index(arrays)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 401, in extract_index
	    raise ValueError("arrays must all be same length")
	ValueError: arrays must all be same length
```

**Comment by tsalo** [comment]
Originally (pre-#447), regressed_dvars_data was overwritten with raw_dvars_data if the lengths didn't match. This is a bug, but it doesn't raise an exception. In #447, @kahinimehta commented out this line, which means that an exception will be raised if the lengths don't match, but at least the bug was apparent. In #579, I went back to overwriting the regressed_dvars_data variable when necessary, hiding the bug once again.

I don't know how to solve this bug, since it probably depends on the temporal mask in some way, but it's something we should deal with at some point.

**Comment by tsalo** [comment]
Also, `plot_svgx` is used in `concantenation.py` and `PlotSVGData`. This means that this bug only affects the line plots in the executive summary.
