### ISSUE TITLE
`--disable-bandpass-filter` breaks ALFF

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#615]
## Summary
It looks like the ALFF interface requires bandpass filtering. I don't know if ALFF itself does, or if this is just a bug in the interface.

## Additional details

- xcp_d version: 0.2.0

### What were you trying to do?

Run xcpd without bandpass filtering.

### What did you expect to happen?

Everything would run successfully, with no bandpass filtering performed.

### What actually happened?

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 920, in build_workflow
    retval["workflow"] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 156, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 448, in init_subject_wf
    bold_postproc_wf = postproc_wf_function(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/bold.py", line 294, in init_boldpostprocess_wf
    alff_compute_wf = init_compute_alff_wf(mem_gb=mem_gbx['timeseries'],
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/restingstate.py", line 104, in init_compute_alff_wf
    alff_compt = pe.Node(ComputeALFF(TR=TR, lowpass=lowpass,
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 564, in __init__
    super(SimpleInterface, self).__init__(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/has_traits.py", line 1434, in trait_set
    setattr(self, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'lowpass' trait of a _ComputeALFFInputSpec instance must be a float, but a value of None <class 'NoneType'> was specified.
```

## Reproducing the bug
Run xcpd with `--disable-bandpass-filter`.

**Comment by tsalo** [comment]
ALFF is invalid without bandpass filtering, so the question becomes whether we should remove the ability to disable the bandpass filter or not calculate ALFF if bandpass filtering is disabled.

**Comment by tsalo** [comment]
Per today's informatics call, we'll automatically disable ALFF if bandpass filtering isn't enabled.
