### ISSUE TITLE
Error using `--dcan-qc` and `--cifti` on nibabies data with multiple output spaces

### ISSUE THREAD

**Issue by lundq163** [PennLINC/xcp_d#684]
## Summary
when running xcpd 0.3.0 on nibabies 22.1.2 derivatives, xcpd seems to be trying to use the wrong T1w transform file from the nibabies anat output. I was using the --dcan-qc flag when this happened; when I run xcpd on the same nibabies derivatives without the flag, then it will process without errors

## Additional details

- xcp_d version: 0.3.0

### What were you trying to do?
test --dcan-qc and --warp-surfaces-native2std flags
### What actually happened?
error produces when using --dcan-qc flag 
## Reproducing the bug
Full .err file output:

```
++ Final vox neighbood: ellipsoid with Nneigh=27 and radii (1.900,1.900,1.900).
++ ReHo (Kendall's W) calculated.
xcp_d failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node get_std2native_transform.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
	    out = function_handle(**args)
	  File "<string>", line 52, in get_std2bold_xforms
	ValueError: Transform does not match BOLD space: MNIInfant != /data/sub-patient01/ses-01/anat/sub-patient01_ses-01_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 564, in main
    xcpd_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node get_std2native_transform.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
	    out = function_handle(**args)
	  File "<string>", line 52, in get_std2bold_xforms
	ValueError: Transform does not match BOLD space: MNIInfant != /data/sub-patient01/ses-01/anat/sub-patient01_ses-01_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_d", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 648, in main
    failed_reports = generate_reports(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/report_core.py", line 182, in generate_reports
    LayoutBuilder(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 400, in __init__
    self.run()
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 501, in run
    tasks_section = TasksSection(tasks=tasks_list, **kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 256, in __init__
    self.run(tasks)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 362, in run
    self.write_bold_gray_row(task_name)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 332, in write_bold_gray_row
    task_file = find_one_file(self.img_path, pattern)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/filemanip.py", line 670, in find_one_file
    one_file = filelist[0]
IndexError: list index out of range
```

**Comment by tsalo** [comment]
Thanks for raising this @lundq163. Can you share the file tree of preprocessed derivatives you inputted to xcpd? Just the subject you ran it on would be good. Can you also share the full xcpd command you used?

**Comment by lundq163** [comment]
here is a brief file tree from the subject folder:
```
derivatives_reconall/sub-patient01/:
  figures  ses-01
  
    derivatives_reconall/sub-patient01/figures:
      sub-patient01_ses-01_desc-about_T1w.html
      sub-patient01_ses-01_desc-conform_T1w.html
      sub-patient01_ses-01_desc-reconall_T1w.svg
      sub-patient01_ses-01_desc-summary_T1w.html
      sub-patient01_ses-01_dseg.svg
      sub-patient01_ses-01_fmapid-auto00000_desc-pepolar_fieldmap.svg
      sub-patient01_ses-01_space-MNI152NLin6Asym_T1w.svg
      sub-patient01_ses-01_space-MNIInfant_cohort-9_T1w.svg
      sub-patient01_ses-01_task-rest_acq-PA_desc-carpetplot_bold.svg
      sub-patient01_ses-01_task-rest_acq-PA_desc-compcorvar_bold.svg
      sub-patient01_ses-01_task-rest_acq-PA_desc-confoundcorr_bold.svg
      sub-patient01_ses-01_task-rest_acq-PA_desc-coreg_bold.svg
      sub-patient01_ses-01_task-rest_acq-PA_desc-rois_bold.svg
      sub-patient01_ses-01_task-rest_acq-PA_desc-summary_bold.html
      sub-patient01_ses-01_task-rest_acq-PA_desc-validation_bold.html
  
    derivatives_reconall/sub-patient01/ses-01:
      anat  fmap  func  log
      
        derivatives_reconall/sub-patient01/ses-01/anat:
          sub-patient01_ses-01_desc-aparcaseg_dseg.nii.gz
          sub-patient01_ses-01_desc-aseg_dseg.nii.gz
          sub-patient01_ses-01_desc-brain_mask.json
          sub-patient01_ses-01_desc-brain_mask.nii.gz
          sub-patient01_ses-01_desc-preproc_T1w.json
          sub-patient01_ses-01_desc-preproc_T1w.nii.gz
          sub-patient01_ses-01_dseg.nii.gz
          sub-patient01_ses-01_from-fsnative_to-T1w_mode-image_xfm.txt
          sub-patient01_ses-01_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5
          sub-patient01_ses-01_from-MNIInfant+9_to-T1w_mode-image_xfm.h5
          sub-patient01_ses-01_from-T1w_to-fsnative_mode-image_xfm.txt
          sub-patient01_ses-01_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5
          sub-patient01_ses-01_from-T1w_to-MNIInfant+9_mode-image_xfm.h5
          sub-patient01_ses-01_hemi-L_inflated.surf.gii
          sub-patient01_ses-01_hemi-L_midthickness.surf.gii
          sub-patient01_ses-01_hemi-L_pial.surf.gii
          sub-patient01_ses-01_hemi-L_smoothwm.surf.gii
          sub-patient01_ses-01_hemi-R_inflated.surf.gii
          sub-patient01_ses-01_hemi-R_midthickness.surf.gii
          sub-patient01_ses-01_hemi-R_pial.surf.gii
          sub-patient01_ses-01_hemi-R_smoothwm.surf.gii
          sub-patient01_ses-01_label-CSF_probseg.nii.gz
          sub-patient01_ses-01_label-GM_probseg.nii.gz
          sub-patient01_ses-01_label-WM_probseg.nii.gz
          sub-patient01_ses-01_space-MNIInfant_cohort-9_desc-brain_mask.json
          sub-patient01_ses-01_space-MNIInfant_cohort-9_desc-brain_mask.nii.gz
          sub-patient01_ses-01_space-MNIInfant_cohort-9_desc-preproc_T1w.json
          sub-patient01_ses-01_space-MNIInfant_cohort-9_desc-preproc_T1w.nii.gz
          sub-patient01_ses-01_space-MNIInfant_cohort-9_dseg.nii.gz
          sub-patient01_ses-01_space-MNIInfant_cohort-9_label-CSF_probseg.nii.gz
          sub-patient01_ses-01_space-MNIInfant_cohort-9_label-GM_probseg.nii.gz
          sub-patient01_ses-01_space-MNIInfant_cohort-9_label-WM_probseg.nii.gz
        
        derivatives_reconall/sub-patient01/ses-01/fmap:
          sub-patient01_ses-01_fmapid-auto00000_desc-coeff_fieldmap.nii.gz
          sub-patient01_ses-01_fmapid-auto00000_desc-epi_fieldmap.nii.gz
          sub-patient01_ses-01_fmapid-auto00000_desc-preproc_fieldmap.json
          sub-patient01_ses-01_fmapid-auto00000_desc-preproc_fieldmap.nii.gz
        
        derivatives_reconall/sub-patient01/ses-01/func:
          sub-patient01_ses-01_task-rest_acq-PA_desc-confounds_timeseries.json
          sub-patient01_ses-01_task-rest_acq-PA_desc-confounds_timeseries.tsv
          sub-patient01_ses-01_task-rest_acq-PA_from-scanner_to-T1w_mode-image_xfm.txt
          sub-patient01_ses-01_task-rest_acq-PA_from-T1w_to-scanner_mode-image_xfm.txt
          sub-patient01_ses-01_task-rest_acq-PA_space-fsLR_den-91k_bold.dtseries.json
          sub-patient01_ses-01_task-rest_acq-PA_space-fsLR_den-91k_bold.dtseries.nii
          sub-patient01_ses-01_task-rest_acq-PA_space-fsLR_den-91k_bold.json
          sub-patient01_ses-01_task-rest_acq-PA_space-MNIInfant_cohort-9_boldref.nii.gz
          sub-patient01_ses-01_task-rest_acq-PA_space-MNIInfant_cohort-9_desc-aparcaseg_dseg.nii.gz
          sub-patient01_ses-01_task-rest_acq-PA_space-MNIInfant_cohort-9_desc-aseg_dseg.nii.gz
          sub-patient01_ses-01_task-rest_acq-PA_space-MNIInfant_cohort-9_desc-brain_mask.json
          sub-patient01_ses-01_task-rest_acq-PA_space-MNIInfant_cohort-9_desc-brain_mask.nii.gz
          sub-patient01_ses-01_task-rest_acq-PA_space-MNIInfant_cohort-9_desc-preproc_bold.json
          sub-patient01_ses-01_task-rest_acq-PA_space-MNIInfant_cohort-9_desc-preproc_bold.nii.gz
        
        derivatives_reconall/sub-patient01/ses-01/log:
          20220907-180454_6c7a2341-9b57-4557-84a8-303863dd097d
        
            derivatives_reconall/sub-patient01/ses-01/log/20220907-180454_6c7a2341-9b57-4557-84a8-303863dd097d:
              nibabies.toml
```

and here is the full run command:
```
#!/bin/bash -l

#SBATCH -J abcd-xcp
#SBATCH -c 8
#SBATCH --mem=96G
#SBATCH -t 3:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lundq163@umn.edu
#SBATCH -p msismall
#SBATCH -o output_logs/xcp_full_%A_%a.out
#SBATCH -e output_logs/xcp_full_%A_%a.err
#SBATCH -A rando149

singularity=`which singularity`

env -i ${singularity} run --cleanenv \
-B /home/faird/shared/code/external/utilities/freesurfer_license/license.txt:/opt/freesurfer/license.txt \
-B /home/feczk001/shared/projects/Jacob_test/WI_test/derivatives_reconall/:/data:ro \
-B /home/feczk001/shared/projects/Jacob_test/WI_test/derivatives_030/:/out \
-B /home/feczk001/shared/projects/Jacob_test/WI_test/work_030/:/work \
/home/faird/shared/code/external/pipelines/xcp_d/xcp_d_0.3.0.sif \
/data /out participant -r 35 -f 0.3 --cifti -m --participant-label patient01 --resource-monitor --omp-nthreads 3 --despike --warp-surfaces-native2std --dcan-qc -vv \
-w /work
```

**Comment by madisoth** [comment]
@tsalo I can help get it tested, I'm working with the same data as @lundq163 .

**Comment by tsalo** [comment]
Great! I'll merge these two PRs as CI starts passing, and I'll ping you in this issue once the updated Docker image is up on DockerHub.

**Comment by tsalo** [comment]
@madisoth `pennlinc/xcp_d:unstable` now has the bug fixes.

**Comment by madisoth** [comment]
Just tested that new build with a clean work and derivatives directory, and am now getting this error:

xcp_d failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node find_nifti_files.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
	    out = function_handle(**args)
	  File "<string>", line 52, in find_nifti_bold_files
	FileNotFoundError: bold file not found: /data/sub-patient01/ses-01/func/sub-patient01_ses-01_task-rest_acq-PA_space-MNI152NLin6Asym*preproc_bold.nii.gz


Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 572, in main
    xcpd_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node find_nifti_files.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
	    out = function_handle(**args)
	  File "<string>", line 52, in find_nifti_bold_files
	FileNotFoundError: bold file not found: /data/sub-patient01/ses-01/func/sub-patient01_ses-01_task-rest_acq-PA_space-MNI152NLin6Asym*preproc_bold.nii.gz



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_d", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 656, in main
    failed_reports = generate_reports(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/report_core.py", line 189, in generate_reports
    LayoutBuilder(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 400, in __init__
    self.run()
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 501, in run
    tasks_section = TasksSection(tasks=tasks_list, **kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 256, in __init__
    self.run(tasks)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 362, in run
    self.write_bold_gray_row(task_name)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/layout_builder.py", line 303, in write_bold_gray_row
    task_file = find_one_file(self.img_path, pattern)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/filemanip.py", line 670, in find_one_file
    one_file = filelist[0]
IndexError: list index out of range

**Comment by tsalo** [comment]
Thanks @madisoth. I might need the full log to make sense of this. Can you run with debug-level logging (`-vvv` instead of `-vv`) and send me the full log? Is this error from the same data that @lundq163 was running on? Can you run it with `--input-type nibabies`?

**Comment by lundq163** [comment]
hey @tsalo, it looks to me like that is the same data i had used earlier

**Comment by madisoth** [comment]
Here's the crashlog, .err and .out with -vvv and --input-type nibabies: 

[crash-20221129-124946-tmadison-find_nifti_files-6fe820c4-987c-4140-8690-a434030d11df.txt](https://github.com/PennLINC/xcp_d/files/10116643/crash-20221129-124946-tmadison-find_nifti_files-6fe820c4-987c-4140-8690-a434030d11df.txt)
[xcp_full_69541087_4294967294.err.txt](https://github.com/PennLINC/xcp_d/files/10116638/xcp_full_69541087_4294967294.err.txt)
[xcp_full_69541087_4294967294.out.txt](https://github.com/PennLINC/xcp_d/files/10116639/xcp_full_69541087_4294967294.out.txt)

**Comment by tsalo** [comment]
Thank you @madisoth. I have discovered another bug:

https://github.com/PennLINC/xcp_d/blob/b54ed02c79705e958d460f08a89670595421d3f2/xcp_d/utils/bids.py#L229-L241

It looks like we need to search for best space among the nifti files, even when we're denoising cifti data. The T1w workflow (split from the anatomical workflow) and the executive summary both require this.

**Comment by tsalo** [comment]
@madisoth I've merged in #695 and the updated version has deployed to Docker. Can you re-pull `unstable` and test it on your data again?

**Comment by madisoth** [comment]
Just tried it and at a glance the output looks good, thanks! @lundq163 and I will test another subject or two and make sure those work too.

**Comment by madisoth** [comment]
I checked the output more closely and looks like the MNI6 template is still being used as the reference, even when the transform applied is MNIInfant

This was the command.txt for t1w_transform:  

`antsApplyTransforms --default-value 0 --dimensionality 3 --float 0 --input /data/sub-patient01/ses-01/anat/sub-patient01_ses-01_desc-preproc_T1w.nii.gz --input-image-type 3 --interpolation LanczosWindowedSinc --output /work/xcpd_wf/single_subject_patient01_wf/t1w_wf/t1w_transform/sub-patient01_ses-01_desc-preproc_T1w_trans.nii.gz --reference-image /home/feczk001/tmadison/.cache/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_T1w.nii.gz --transform /data/sub-patient01/ses-01/anat/sub-patient01_ses-01_from-T1w_to-MNIInfant+9_mode-image_xfm.h5`

**Comment by tsalo** [comment]
That's definitely a bug, but I think it's distinct enough from this issue to be worth opening a new one.

**Comment by tsalo** [comment]
@madisoth @lundq163 I've opened #701 about the T1w output space. Do you think we can close this issue?
