### ISSUE TITLE
Trouble running aroma: Could not find mixing matrix

### ISSUE THREAD

**Issue by andreifoldes** [PennLINC/xcp_d#792]
## Summary

Could not find mixing matrix
## Additional details

- xcp_d version: 032

### What were you trying to do?
Running xcp_d with aroma nuisance model after successfully running it with 36P

### What did you expect to happen?
Successful postprocessing.

### What actually happened?
```
Node: xcpd_wf.single_subject_0122026_wf.nifti_postprocess_1_wf.consolidate_confounds_node
Working directory: /cubric/collab/396_cogdist/tamas_tmp_work/xcpd_wf/single_subject_0122026_wf/nifti_postprocess_1_wf/consolidate_confounds_node

Node inputs:

custom_confounds_file = None
function_str = def consolidate_confounds(
    img_file,
    params,
    custom_confounds_file=None,
):
    Combine confounds files into a single tsv.

    Parameters
    ----------
    img_file : str
        bold file
    params
    custom_confounds_folder : str or None
        Path to custom confounds tsv. May be None.

    Returns
    -------
    out_file : str
        Path to combined tsv.
    """
    import os

    from xcp_d.utils.confounds import load_confound_matrix

    confounds_df = load_confound_matrix(
        img_file=img_file,
        params=params,
        custom_confounds=custom_confounds_file,
    )

    out_file = os.path.abspath("confounds.tsv")
    confounds_df.to_csv(out_file, sep="\t", index=False)

    return out_file

img_file = /cubric/collab/396_cogdist/bids/derivatives/sub-0122026/ses-2/func/sub-0122026_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
params = aroma_gsr

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node consolidate_confounds_node.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
	    out = function_handle(**args)
	  File "<string>", line 25, in consolidate_confounds
	  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/confounds.py", line 434, in load_confound_matrix
	    ica_mixing_matrix = _get_mixing_matrix(img_file)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/confounds.py", line 458, in _get_mixing_matrix
	    raise FileNotFoundError(f"Could not find mixing matrix for {img_file}")
	FileNotFoundError: Could not find mixing matrix for /cubric/collab/396_cogdist/bids/derivatives/sub-0122026/ses-2/func/sub-0122026_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
```

## Reproducing the bug

```
srun singularity run --cleanenv --bind /.../.../.../bids/derivatives --bind /.../.../...//xcp_d_aroma --bind /.../.../.../ /.../.../.../images/xcp_d-version-032.simg /.../.../.../bids/derivatives/.../.../.../xcp_d_aroma participant --participant-label $SUBID -f 0.5 -w /.../.../.../ --input-type fmriprep --nthreads 12 --nuisance-regressors aroma_gsr --despike
```

**Comment by tsalo** [comment]
Can you show the tree for your preprocessed derivatives?

**Comment by andreifoldes** [comment]
this would be a sample participants folder structure within `derivatives`..
its a two session multi-echo resting-state ds, with some residual conn-toolbox files generated with *fMRIPrep* 21.0.2
```
|-- anat
|   |--  anat/esub-0122025_space-MNI152NLin2009cAsym_res-2_label-CSF_probseg.nii
|   |--  anat/esub-0122025_space-MNI152NLin2009cAsym_res-2_label-GM_probseg.nii
|   |--  anat/esub-0122025_space-MNI152NLin2009cAsym_res-2_label-WM_probseg.nii
|   |--  anat/sub-0122025_desc-aparcaseg_dseg.nii.gz
|   |--  anat/sub-0122025_desc-aseg_dseg.nii.gz
|   |--  anat/sub-0122025_desc-brain_mask.json
|   |--  anat/sub-0122025_desc-brain_mask.nii.gz
|   |--  anat/sub-0122025_desc-preproc_T1w.json
|   |--  anat/sub-0122025_desc-preproc_T1w.nii.gz
|   |--  anat/sub-0122025_dseg.nii.gz
|   |--  anat/sub-0122025_from-fsnative_to-T1w_mode-image_xfm.txt
|   |--  anat/sub-0122025_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
|   |--  anat/sub-0122025_from-T1w_to-fsnative_mode-image_xfm.txt
|   |--  anat/sub-0122025_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
|   |--  anat/sub-0122025_hemi-L_inflated.surf.gii
|   |--  anat/sub-0122025_hemi-L_midthickness.surf.gii
|   |--  anat/sub-0122025_hemi-L_pial.surf.gii
|   |--  anat/sub-0122025_hemi-L_smoothwm.surf.gii
|   |--  anat/sub-0122025_hemi-R_inflated.surf.gii
|   |--  anat/sub-0122025_hemi-R_midthickness.surf.gii
|   |--  anat/sub-0122025_hemi-R_pial.surf.gii
|   |--  anat/sub-0122025_hemi-R_smoothwm.surf.gii
|   |--  anat/sub-0122025_label-CSF_probseg.nii.gz
|   |--  anat/sub-0122025_label-GM_probseg.nii.gz
|   |--  anat/sub-0122025_label-WM_probseg.nii.gz
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_desc-preproc_T1w.json
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_desc-preproc_T1w.nii
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_desc-preproc_T1w.nii.gz
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_dseg.nii.gz
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_label-CSF_probseg.nii
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_label-CSF_probseg.nii.gz
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_label-GM_probseg.nii
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_label-GM_probseg.nii.gz
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_label-WM_probseg.nii
|   |--  anat/sub-0122025_space-MNI152NLin2009cAsym_res-2_label-WM_probseg.nii.gz
|-- figures
|   |--  figures/sub-0122025_desc-conform_T1w.html
|   |--  figures/sub-0122025_desc-reconall_T1w.svg
|   |--  figures/sub-0122025_dseg.svg
|   |--  figures/sub-0122025_ses-1_desc-about_T1w.html
|   |--  figures/sub-0122025_ses-1_desc-summary_T1w.html
|   |--  figures/sub-0122025_ses-1_task-rest_desc-bbregister_bold.svg
|   |--  figures/sub-0122025_ses-1_task-rest_desc-carpetplot_bold.svg
|   |--  figures/sub-0122025_ses-1_task-rest_desc-compcorvar_bold.svg
|   |--  figures/sub-0122025_ses-1_task-rest_desc-confoundcorr_bold.svg
|   |--  figures/sub-0122025_ses-1_task-rest_desc-rois_bold.svg
|   |--  figures/sub-0122025_ses-1_task-rest_desc-summary_bold.html
|   |--  figures/sub-0122025_ses-1_task-rest_desc-validation_bold.html
|   |--  figures/sub-0122025_ses-2_task-rest_desc-bbregister_bold.svg
|   |--  figures/sub-0122025_ses-2_task-rest_desc-carpetplot_bold.svg
|   |--  figures/sub-0122025_ses-2_task-rest_desc-compcorvar_bold.svg
|   |--  figures/sub-0122025_ses-2_task-rest_desc-confoundcorr_bold.svg
|   |--  figures/sub-0122025_ses-2_task-rest_desc-rois_bold.svg
|   |--  figures/sub-0122025_ses-2_task-rest_desc-summary_bold.html
|   |--  figures/sub-0122025_ses-2_task-rest_desc-validation_bold.html
|   |--  figures/sub-0122025_space-MNI152NLin2009cAsym_T1w.svg
|-- log
|   |--  log/20220513-170843_5f321b4f-16cb-40be-8e46-e1d23aa38067
|   |   |--  log/20220513-170843_5f321b4f-16cb-40be-8e46-e1d23aa38067/fmriprep.toml
|   |--  log/20220725-060735_9bef7a90-b472-4208-b3de-ea6d93466612
|   |   |--  log/20220725-060735_9bef7a90-b472-4208-b3de-ea6d93466612/fmriprep.toml
|-- ses-1
|   |--  ses-1/anat
|   |   |--  ses-1/anat/sub-0122025_ses-1_from-orig_to-T1w_mode-image_xfm.txt
|   |--  ses-1/func
|   |   |--  ses-1/func/scrubbing_sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_timeseries.mat
|   |   |--  ses-1/func/scrubbing_sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_timeseries.mat
|   |   |--  ses-1/func/ssub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_desc-confounds_timeseries.json
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_desc-confounds_timeseries.tsv
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_echo-1_desc-preproc_bold.json
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_echo-1_desc-preproc_bold.nii.gz
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_echo-2_desc-preproc_bold.json
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_echo-2_desc-preproc_bold.nii.gz
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_echo-3_desc-preproc_bold.json
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_echo-3_desc-preproc_bold.nii.gz
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_from-scanner_to-T1w_mode-image_xfm.txt
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_from-T1w_to-scanner_mode-image_xfm.txt
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_boldref.nii.gz
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-aparcaseg_dseg.nii.gz
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-aseg_dseg.nii.gz
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_a_comp_cor.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_c_comp_cor.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_cosine.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_motion_outlier.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_rot.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_t_comp_cor.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_timeseries.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_trans.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_w_comp_cor.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.realignment.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.scrubbing.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_a_comp_cor.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_c_comp_cor.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_cosine.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_motion_outlier.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_rot.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_t_comp_cor.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_timeseries.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_trans.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_w_comp_cor.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.realignment.mat
|   |   |--  ses-1/func/sub-0122025_ses-1_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.scrubbing.mat
|-- ses-2
|   |--  ses-2/anat
|   |   |--  ses-2/anat/sub-0122025_ses-2_from-orig_to-T1w_mode-image_xfm.txt
|   |--  ses-2/func
|   |   |--  ses-2/func/scrubbing_sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_timeseries.mat
|   |   |--  ses-2/func/scrubbing_sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_timeseries.mat
|   |   |--  ses-2/func/ssub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_desc-confounds_timeseries.json
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_desc-confounds_timeseries.tsv
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_echo-1_desc-preproc_bold.json
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_echo-1_desc-preproc_bold.nii.gz
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_echo-2_desc-preproc_bold.json
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_echo-2_desc-preproc_bold.nii.gz
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_echo-3_desc-preproc_bold.json
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_echo-3_desc-preproc_bold.nii.gz
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_from-scanner_to-T1w_mode-image_xfm.txt
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_from-T1w_to-scanner_mode-image_xfm.txt
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_boldref.nii.gz
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-aparcaseg_dseg.nii.gz
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-aseg_dseg.nii.gz
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_a_comp_cor.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_c_comp_cor.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_cosine.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_motion_outlier.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_rot.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_t_comp_cor.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_timeseries.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_trans.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.QC_w_comp_cor.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.realignment.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.scrubbing.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_a_comp_cor.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_c_comp_cor.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_cosine.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_motion_outlier.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_rot.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_t_comp_cor.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_timeseries.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_trans.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.QC_w_comp_cor.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.realignment.mat
|   |   |--  ses-2/func/sub-0122025_ses-2_task-rest_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.scrubbing.mat

```

**Comment by tsalo** [comment]
Thank you. It doesn't look like you have AROMA-related derivatives. Did you run fMRIPrep with AROMA enabled (i.e., with the `--use-aroma` flag)?

**Comment by andreifoldes** [comment]
Ah, no I did not! I thought that xcp_d would be doing that part. Thank you, I will re-run fmriprep!

**Comment by tsalo** [comment]
In that case, I'll close this. Feel free to reopen if there are issues with AROMA after re-running fMRIPrep.
