### ISSUE TITLE
xcp_d cannot access miniconda with singularity

### ISSUE THREAD

**Issue by StevenGeysen** [PennLINC/xcp_d#793]
## Summary
Using the singularity image, we run into a permission error `PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.8/site-packages/.wh.pip-20.2.4-py3.8.egg-info'`. It appears that xcp_d creates a miniconda environment that it cannot access later on.

## Additional details

- xcp_d version: 0.3.2 (latest)

### What were you trying to do?
We tried to apply xcp_d to fMRIPrep output.
### What did you expect to happen?
We expected the scripts to run without errors and end up with regressed data.
### What actually happened?
The process breaks and returns `PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.8/site-packages/.wh.pip-20.2.4-py3.8.egg-info'`

The full error:
```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-viusok7q because the default path (/home/xcp_d/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_d", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 547, in main
    from xcp_d.utils.sentry import sentry_setup
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/__init__.py", line 5, in <module>
    from xcp_d.utils import (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/concatenation.py", line 13, in <module>
    from nilearn.image import concat_imgs
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/__init__.py", line 39, in <module>
    import pkg_resources
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 558, in _build_master
    ws = cls()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 551, in __init__
    self.add_entry(entry)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 607, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2060, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2125, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2585, in from_location
    return cls(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2985, in _reload_version
    md_version = self._get_version()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2767, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2551, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2762, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1903, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1890, in get_metadata
    with io.open(self.path, encoding='utf-8', errors="replace") as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.8/site-packages/.wh.pip-20.2.4-py3.8.egg-info'
```

## Reproducing the bug

```
singularity run --cleanenv \
-B ~/petTOAD/data/preprocessed/fmriprep:/data:ro \
-B ~/petTOAD/data/preprocessed/xcp_d:/out \
-B ~/petTOAD/data/preprocessed/temp:/work \
~/petTOAD/singims/xcp_d-latest.simg /data /out participant -w /work
```

Thank you for your time!

**Comment by tsalo** [comment]
I chatted with @mattcieslak offline about this and he recommended using `--containall` in your `singularity run` call. It looks like Singularity is looking in your home directory instead of the container's xcp_d home directory.

**Comment by StevenGeysen** [comment]
Thank you for your quick response.

When I add `--containall`, nothing changes.

The full, new, script:
```
singularity run --containall --cleanenv \
-B ~/petTOAD/data/preprocessed/fmriprep:/data:ro \
-B ~/petTOAD/data/preprocessed/xcp_d:/out \
-B ~/petTOAD/data/preprocessed/temp:/work \
~/petTOAD/singims/xcp_d-latest.simg /data /out participant -w /work
```
and the full "new" error:
```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-nj0r_gy2 because the default path (/home/xcp_d/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_d", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 547, in main
    from xcp_d.utils.sentry import sentry_setup
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/__init__.py", line 5, in <module>
    from xcp_d.utils import (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/concatenation.py", line 13, in <module>
    from nilearn.image import concat_imgs
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/__init__.py", line 39, in <module>
    import pkg_resources
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 558, in _build_master
    ws = cls()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 551, in __init__
    self.add_entry(entry)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 607, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2060, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2125, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2585, in from_location
    return cls(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2985, in _reload_version
    md_version = self._get_version()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2767, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2551, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2762, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1903, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1890, in get_metadata
    with io.open(self.path, encoding='utf-8', errors="replace") as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.8/site-packages/.wh.pip-20.2.4-py3.8.egg-info'
```

**Comment by mattcieslak** [comment]
What was your singularity build command?

**Comment by StevenGeysen** [comment]
`singularity build ~/petTOAD/singims/xcp_d-latest.simg docker://pennlinc/xcp_d:latest`

**Comment by tsalo** [comment]
I think https://github.com/nipreps/mriqc/issues/647 might be a similar issue. I'm going to look at the changes to the Dockerfile they made.

**Comment by tsalo** [comment]
@StevenGeysen I've pushed what I think is a fix. Would you be willing/able to pull version 0.3.3rc2 and try it out?

**Comment by StevenGeysen** [comment]
I used `singularity build ~/petTOAD/singims/xcp_d_033rc2.simg docker://pennlinc/xcp_d:0.3.3rc2` to build the image, and to use the image I had the same as before (with the new one):
```
singularity run --containall --cleanenv \
-B ~/petTOAD/data/preprocessed/fmriprep:/data:ro \
-B ~/petTOAD/data/preprocessed/xcp_d:/out \
-B ~/petTOAD/data/preprocessed/temp:/work \
~/petTOAD/singims/xcp_d_033rc2.simg /data /out participant -w /work
```
But the output looks the same
```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-r0scje74 because the default path (/home/xcp_d/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_d", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 547, in main
    from xcp_d.utils.sentry import sentry_setup
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/__init__.py", line 5, in <module>
    from xcp_d.utils import (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/concatenation.py", line 13, in <module>
    from nilearn.image import concat_imgs
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/__init__.py", line 39, in <module>
    import pkg_resources
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 558, in _build_master
    ws = cls()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 551, in __init__
    self.add_entry(entry)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 607, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2060, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2125, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2585, in from_location
    return cls(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2985, in _reload_version
    md_version = self._get_version()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2767, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2551, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2762, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1903, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1890, in get_metadata
    with io.open(self.path, encoding='utf-8', errors="replace") as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.8/site-packages/.wh.pip-20.2.4-py3.8.egg-info'
```

**Comment by tsalo** [comment]
@StevenGeysen sorry for the delay. I've made another maintenance release: 0.3.3rc3. Would you mind trying that one out?

**Comment by StevenGeysen** [comment]
No problem, I appriciate all the time and effort you put into this.

To build the image:
```
singularity build ~/petTOAD/singims/xcp_d_033rc3.simg docker://pennlinc/xcp_d:0.3.3rc3
```
To run the image:
```
singularity run --containall --cleanenv \
-B ~/petTOAD/data/preprocessed/fmriprep:/data:ro \
-B ~/petTOAD/data/preprocessed/xcp_d:/out \
-B ~/petTOAD/data/preprocessed/temp:/work \
~/petTOAD/singims/xcp_d_033rc3.simg /data /out participant -w /work
```
The result:
```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-hezkyw12 because the default path (/home/xcp_d/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_d", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 547, in main
    from xcp_d.utils.sentry import sentry_setup
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/__init__.py", line 5, in <module>
    from xcp_d.utils import (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/concatenation.py", line 13, in <module>
    from nilearn.image import concat_imgs
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/__init__.py", line 39, in <module>
    import pkg_resources
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 558, in _build_master
    ws = cls()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 551, in __init__
    self.add_entry(entry)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 607, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2060, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2125, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2585, in from_location
    return cls(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2985, in _reload_version
    md_version = self._get_version()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2767, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2551, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2762, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1903, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1890, in get_metadata
    with io.open(self.path, encoding='utf-8', errors="replace") as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.8/site-packages/.wh.pip-20.2.4-py3.8.egg-info'
```

**Comment by tsalo** [comment]
I've made another release where there should hopefully be only one version of pip. Can you give `0.3.3rc4` a try?

**Comment by StevenGeysen** [comment]
To build the image:
```
singularity build ~/petTOAD/singims/xcp_d_033rc4.simg docker://pennlinc/xcp_d:0.3.3rc4
```
To run the image:
```
singularity run --containall --cleanenv \
-B ~/petTOAD/data/preprocessed/fmriprep:/data:ro \
-B ~/petTOAD/data/preprocessed/xcp_d:/out \
-B ~/petTOAD/data/preprocessed/temp:/work \
~/petTOAD/singims/xcp_d_033rc4.simg /data /out participant -w /work
```
The result:
```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-hrqrc2or because the default path (/home/xcp_d/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xcp_d", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 547, in main
    from xcp_d.utils.sentry import sentry_setup
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/__init__.py", line 5, in <module>
    from xcp_d.utils import (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/concatenation.py", line 13, in <module>
    from nilearn.image import concat_imgs
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/__init__.py", line 39, in <module>
    import pkg_resources
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 558, in _build_master
    ws = cls()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 551, in __init__
    self.add_entry(entry)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 607, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2060, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2125, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2585, in from_location
    return cls(
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2985, in _reload_version
    md_version = self._get_version()
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2767, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2551, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2762, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1903, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1890, in get_metadata
    with io.open(self.path, encoding='utf-8', errors="replace") as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.8/site-packages/.wh.pip-20.2.4-py3.8.egg-info'
```
I also tried to run it with `-B /home/StevenGeysen/petTOAD/` instead of `-B ~/petTOAD` but the result was the same.

**Comment by tsalo** [comment]
Thanks @StevenGeysen for checking. AFAICT, the problematic whiteout file/folder (`.wh.pip-20.2.4-py3.8.egg-info`) doesn't exist in the xcp_d_build Docker image or the xcp_d Docker image, and I have no clue where `pip` version `20.2.4` would even come from...

@StevenGeysen can you check if `.wh.pip-20.2.4-py3.8.egg-info` exists in the initially built Singularity image? You should be able to enter the image with `singularity shell` after you build it.

**Comment by StevenGeysen** [comment]
Yes, it does exists!

**Comment by tsalo** [comment]
That means it's not created by any of xcp_d's dependencies (including nilearn) when they're imported. I just looked in the `0.3.3rc4` Docker image, and the folder _doesn't_ exist. So I think Singularity is creating it during the build process.

**Comment by tsalo** [comment]
Aha! There's a closed Singularity issue that seems related: https://github.com/apptainer/singularity/issues/884. It looks like their fix was merged in January 2018, so Singularity versions >=2.4.3 should have that fix in. What version of Singularity are you using?

**Comment by StevenGeysen** [comment]
To build the image I used `v2.4.6`. So I tried building `xcp_d:latest` with the most recent version I can acces here `v3.8.1-1.el8`. It seems to work now. I get a differnt error (`OSError: [Errno 28] No space left on device`) but I assume that this is something I have to solve on my end.

Thanks a lot for all your help!

**Comment by tsalo** [comment]
Thank goodness. I'm not sure why 2.4.6 would have the bug, but I could have misread the Singularity repo's release notes. In any case, we'll add info about Singularity requirements to our documentation and update out bug report template to ask for the Singularity/Docker version.

Sorry for the long debugging process, and thank you for your patience.
