### ISSUE TITLE
Error with processing HCP data using xcp-d

### ISSUE THREAD

**Issue by WY-SHI** [PennLINC/xcp_d#867]
## Summary
In order to do post-processing of HCP data, I try the follow command:
```
singularity run -B /in_path/100206:/data -B /out_path/xcp_d:/out -B /work_path/tmp:/work --cleanenv xcp_d.simg /data /out participant --input-type hcp -w /work
```
However, some error occurs as follow:
```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 800, in build_workflow
    convert_to_bids(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/hcp2fmriprep.py", line 85, in convert_hcp2bids
    convert_hcp_to_bids_single_subject(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/hcp2fmriprep.py", line 260, in convert_hcp_to_bids_single_subject
    TR = nb.load(bold_nifti_orig).header.get_zooms()[-1]  # repetition time
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabel/loadsave.py", line 89, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/data/T1w/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz'
```
I tried to locate the error and found that the file rfMRI_REST1_LR.nii.gz is in the file `/data/MNINonLinear/Results/rfMRI_REST1_LR/`ranther than `/data/T1w/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz`. Obviously, the space of files in the two paths is different, so I cannot confirm whether it is correct to modify the path directly. I hope to get your reply, thank you!

## Additional details

- xcp_d version: 0.4.0rc2

**Comment by WY-SHI** [comment]
> Hello! Thank you for letting us know about this.
> 
> Could you confirm when the HCP-YA data you're trying to run XCP on was downloaded? This feature was built with testing on a version of HCPYA downloaded in February 2023, and so might not be compatible with older versions.

Thanks for your reply, and the HCP data I used is indeed the old version.

**Comment by kahinimehta** [comment]
Thank you for letting us know - we will add the HCPYA version we used to our documentation!
